version: '3'
services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    